"""Seed the canonical repository: config, agreement, reconcile workflow, key.

The workflow is the sensitive artifact here. It runs inside the repository that
holds signer data, with a deploy key that can write the coverage projection, and
it consumes contributor-supplied strings. DR-013 is workflow injection through
exactly that path, so the generated YAML never interpolates event data into
`run:` or `env:` and declares least-privilege `permissions:` explicitly.
"""

from __future__ import annotations

import base64
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "core"))

from dracla.github import GitHubError, GitHubHost      # noqa: E402
from dracla.githost import NotFound                    # noqa: E402

from .config import CONFIG_PATH, ProjectConfig         # noqa: E402
from .errors import CliError                           # noqa: E402

WORKFLOW_PATH = ".github/workflows/dracla-reconcile.yml"
AGREEMENT_DIR = "agreements"

# Daily, not six-hourly: these minutes bill to the ADOPTER's organization and
# come out of their whole 2,000/month private-repo allowance. Only orphan
# clearing is latency-sensitive, and the Worker clears most opportunistically.
# See design §9.2.
RECONCILE_WORKFLOW = """\
# Generated by `dracla install`. Edit via `dracla config`, not by hand.
#
# Runs inside the canonical records repository, where signer data legitimately
# lives. Two rules keep that safe and both are deliberate:
#
#   - `permissions:` is least-privilege and explicit. Without it the job would
#     inherit the repository default, and a compromised step could rewrite the
#     append-only history REQ-REC-4 says DraCLA must never touch.
#   - No step interpolates event content into `run:` or `env:`. Signer fields
#     are untrusted input (REQ-SEC-8) and this job holds a cross-repo write
#     credential; a `${{ }}` expansion of a supplied legal name would be command
#     execution on a runner that can forge the merge gate.
name: dracla reconcile

on:
  push:
    branches: [events]
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: dracla-reconcile
  cancel-in-progress: false

jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: events
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dracla
        run: pip install "dracla==${DRACLA_VERSION}"
        env:
          DRACLA_VERSION: "%(version)s"

      - name: Replay, verify, and repair the projection
        run: dracla reconcile --coverage-key-file "$RUNNER_TEMP/coverage.key"
        env:
          DRACLA_COVERAGE_DEPLOY_KEY: ${{ secrets.DRACLA_COVERAGE_DEPLOY_KEY }}
          DRACLA_COVERAGE_REPO: "%(coverage_repo)s"
"""


class Seeder:
    def __init__(self, token: str, records_repo: str, *, dry_run: bool = False):
        self.host = GitHubHost(repo=records_repo, token=token)
        self.repo = records_repo
        self.dry_run = dry_run

    def _put(self, path: str, content: str, message: str) -> str:
        """Write a file, creating or updating. Returns 'created'/'updated'/'skipped'."""
        try:
            existing, blob = self.host.read("main", path)
            if existing == content:
                return "skipped"
            action, base = "updated", blob
        except NotFound:
            action, base = "created", None

        if self.dry_run:
            return action + " (dry-run)"
        self.host.put("refs/heads/main", path, content, base_blob_sha=base)
        return action

    def seed_config(self, cfg: ProjectConfig) -> str:
        return self._put(CONFIG_PATH, cfg.to_json(), "dracla: project config")

    def seed_agreement(self, cfg: ProjectConfig, text: str, version: str) -> str:
        path = f"{AGREEMENT_DIR}/{cfg.agreement_id}/{version}.md"
        return self._put(path, text, f"dracla: agreement {cfg.agreement_id}@{version}")

    def seed_workflow(self, coverage_repo: str, version: str) -> str:
        body = RECONCILE_WORKFLOW % {"version": version, "coverage_repo": coverage_repo}
        return self._put(WORKFLOW_PATH, body, "dracla: reconcile workflow")

    def ensure_events_branch(self) -> str:
        """Create the append-only events branch if absent.

        Orphaned deliberately: `REQ-REC-3` makes commit ancestry the
        authoritative event order, so the first event must not inherit a
        default-branch history that means nothing.
        """
        if self.host.head("refs/heads/events") is not None:
            return "exists"
        if self.dry_run:
            return "created (dry-run)"
        sha = self.host.commit(
            parent=None,
            changes={"README.md":
                     "# Canonical CLA events\n\n"
                     "Append-only. One logical event per commit; commit "
                     "ancestry is the authoritative order. Never rewrite this "
                     "branch.\n"},
            message="dracla: initialize events branch")
        self.host.update_ref("refs/heads/events", sha)
        return "created"

    def add_deploy_key(self, coverage_repo: str, public_key: str) -> str:
        """Give the reconciler write access to the coverage repo, and only that.

        A deploy key is per-repository by construction, which is the point: the
        reconciler can write the projection and nothing else. It is stored in
        the canonical repo's Actions secrets — repository *settings*, not
        repository *contents*, so `REQ-SEC-4`'s prohibition on secrets in
        records repositories is not breached (§8.1.2).
        """
        if self.dry_run:
            return "would add"
        try:
            self.host._req("POST", f"/repos/{coverage_repo}/keys", {
                "title": "dracla-reconciler",
                "key": public_key,
                "read_only": False,
            })
        except GitHubError as e:
            if e.status == 422 and "already in use" in e.body:
                return "exists"
            raise CliError(f"could not add deploy key to {coverage_repo}: {e}") from None
        return "added"
