"""The Actions workflow install seeds (§6.10.2).

`dracla reconcile` does not exist yet (milestone M2). Install therefore seeds a
placeholder that states its own absence, rather than the real reconciler.

That distinction is not pedantry. A previous implementation seeded a workflow
invoking `dracla reconcile` and reading a deploy-key secret, neither of which
existed: install reported success, and the workflow failed on the first
signature — the worst possible moment to discover it. A workflow that cannot run
should say so at install time.
"""

from __future__ import annotations

RECONCILE_IMPLEMENTED = False

WORKFLOW_PATH = ".github/workflows/dracla-reconcile.yml"

PLACEHOLDER = """\
# Generated by `dracla install` (dracla %(version)s). Do not edit by hand.
#
# DraCLA reconciliation is not implemented yet. This placeholder exists so the
# branch layout is right and the workflow sits where it will run, without
# pretending to work: `dracla reconcile` and the coverage deploy key both arrive
# in milestone M2.
#
# Until then the coverage projection at %(coverage_repo)s is written only by the
# signing path, with no independent verification.
name: dracla reconcile (not yet implemented)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Explain
        run: |
          echo "dracla reconcile is not implemented yet (milestone M2)."
          echo "Re-run 'dracla install' after upgrading dracla to enable it."
          exit 1
"""

# The real reconciler, seeded once RECONCILE_IMPLEMENTED is true.
#
# Two properties are deliberate and are asserted by tests, because this job runs
# where signer data lives and holds a credential that can write the coverage
# projection:
#
#   - `permissions:` is least-privilege and explicit. Inherited defaults would
#     let a compromised step rewrite the append-only history REQ-REC-4 says
#     DraCLA must never touch.
#   - No step interpolates event content into `run:` or `env:`. Signer fields
#     are untrusted input (REQ-SEC-8), so a `${{ }}` expansion of a supplied
#     legal name would be command execution on a runner that can forge the
#     merge gate.
#
# Daily rather than hourly: these minutes bill to the ADOPTER's organization,
# against their whole private-repo allowance (§9.2).
RECONCILE = """\
# Generated by `dracla install` (dracla %(version)s). Do not edit by hand.
name: dracla reconcile

on:
  push:
    branches: [%(events_branch)s]
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: dracla-reconcile
  cancel-in-progress: false

jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      # Pinned by commit digest, never a floating tag (design §9, supply
      # chain): this workflow runs inside the adopter's PII repository on a
      # runner holding the coverage deploy key, so a mutable reference means
      # one push to the action's repo executes attacker-chosen code in every
      # adopter's records repo at once.
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
        with:
          ref: %(events_branch)s
          fetch-depth: 0

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        with:
          python-version: "3.12"

      # M2 must add provenance verification here before this template is
      # seeded: §9 requires the workflow to verify the release's attestation
      # before running it, and a version pin alone does not do that.
      - name: Install dracla
        run: pip install "dracla==${DRACLA_VERSION}"
        env:
          DRACLA_VERSION: "%(version)s"

      - name: Replay, verify, and repair the projection
        run: dracla reconcile
        env:
          DRACLA_COVERAGE_DEPLOY_KEY: ${{ secrets.DRACLA_COVERAGE_DEPLOY_KEY }}
          DRACLA_COVERAGE_REPO: "%(coverage_repo)s"
"""


def render(coverage_repo: str, version: str, events_branch: str) -> str:
    template = RECONCILE if RECONCILE_IMPLEMENTED else PLACEHOLDER
    return template % {"version": version, "coverage_repo": coverage_repo,
                       "events_branch": events_branch}
